INSERT INTO ppa_indicadores (
    codigo,
    numero_programa,
    nome,
    objetivo,
    justificativa,
    publico_alvo,
    ods_codigo,
    ods_descricao,
    meta_ods,
    unidade_medida,
    indice_recente,
    indice_futuro,
    memoria_calculo,
    fonte_dados,
    criterio_utilizado,
    forma_calculo,
    resultado_esperado,
    tipo_alimentacao,
    periodicidade,
    status
)
SELECT
    'PPA-ERRADICAR-POBREZA',
    NULL,
    'Ate 2030, erradicar a pobreza',
    'Acompanhar o total de familias em situacao de pobreza no municipio para apoio ao planejamento do PPA.',
    'Consolidar anualmente o quantitativo de familias do CadUnico enquadradas no criterio de elegibilidade do Programa Bolsa Familia.',
    'Familias cadastradas no CadUnico com renda familiar mensal per capita de ate R$ 218,00.',
    'ODS 1',
    'Erradicacao da pobreza',
    'Ate 2030, erradicar a pobreza extrema para todas as pessoas em todos os lugares.',
    'familias',
    NULL,
    NULL,
    'CECAD Total de Familias em Situacao de Pobreza, segundo criterio de elegibilidade para o Programa Bolsa Familia (renda per capita de R$0,00 ate R$218,00).',
    'CECAD - base de dezembro do ano anterior.',
    'Sao consideradas em situacao de pobreza todas as familias cadastradas no CadUnico cuja renda familiar mensal per capita esteja entre R$ 0,00 e R$ 218,00.',
    'Contagem distinta de familias do municipio com renda per capita entre R$ 0,00 e R$ 218,00 na base de dezembro do ano anterior.',
    'Registrar anualmente o total consolidado de familias em situacao de pobreza.',
    'automatico',
    'anual',
    1
WHERE NOT EXISTS (
    SELECT 1 FROM ppa_indicadores WHERE codigo = 'PPA-ERRADICAR-POBREZA'
);

INSERT INTO ppa_indicadores (
    codigo,
    numero_programa,
    nome,
    objetivo,
    justificativa,
    publico_alvo,
    ods_codigo,
    ods_descricao,
    meta_ods,
    unidade_medida,
    indice_recente,
    indice_futuro,
    memoria_calculo,
    fonte_dados,
    criterio_utilizado,
    forma_calculo,
    resultado_esperado,
    tipo_alimentacao,
    periodicidade,
    status
)
SELECT
    'PPA-ACOMPANHAR-FAMILIAS-PBF',
    149,
    'Acompanhar 10% das familias beneficiarias do Programa Bolsa Familia inscritas no CadUnico',
    'Monitorar o acompanhamento socioassistencial das familias beneficiarias do Programa Bolsa Familia inscritas no CadUnico, considerando a meta minima anual de 10%.',
    'Atender ao acompanhamento continuado das familias beneficiarias do PBF a partir do cruzamento entre a base CECAD de referencia e os registros mensais do RMA CRAS.',
    'Familias beneficiarias do Programa Bolsa Familia inscritas no CadUnico.',
    'ODS 1',
    'Erradicar pobreza',
    'Acompanhar a evolucao anual do percentual de familias acompanhadas em relacao a base de referencia do municipio.',
    'percentual de familias',
    7.0000,
    10.0000,
    'RMA CRAS B.2 - Novas familias inseridas em acompanhamento beneficiarias do PBF. Total de familias com PBF no CECAD da referencia configurada x 0,10 = meta. Total de novas familias acompanhadas B.2 / Total de familias com PBF = percentual alcancado.',
    'CECAD para base de familias beneficiarias do PBF e RMA CRAS - bloco B.2 para o acompanhamento mensal.',
    'Consideram-se apenas familias com marc_pbf = 1 na base familia de referencia e os novos acompanhamentos informados no campo B.2 do RMA CRAS no ano de apuracao.',
    'Total de familias com PBF na base familia de referencia x 10% = meta quantitativa. Soma mensal do B.2 do RMA CRAS no ano / total da base familia x 100 = percentual alcancado.',
    'Demonstrar a evolucao do acompanhamento das familias beneficiarias do PBF ao longo do ano, com total acumulado e comparativo com a meta.',
    'automatico',
    'mensal',
    1
WHERE NOT EXISTS (
    SELECT 1 FROM ppa_indicadores WHERE codigo = 'PPA-ACOMPANHAR-FAMILIAS-PBF'
);

INSERT INTO ppa_indicadores (
    codigo,
    numero_programa,
    nome,
    objetivo,
    justificativa,
    publico_alvo,
    ods_codigo,
    ods_descricao,
    meta_ods,
    unidade_medida,
    indice_recente,
    indice_futuro,
    memoria_calculo,
    fonte_dados,
    criterio_utilizado,
    forma_calculo,
    resultado_esperado,
    tipo_alimentacao,
    periodicidade,
    status
)
SELECT
    'PPA-ACOMPANHAR-FAMILIAS-MEIO-SM-PAIF',
    148,
    'Acompanhar 10% das familias com renda per capita de ate 1/2 salario minimo no CadUnico pelo PAIF',
    'Monitorar o acompanhamento socioassistencial das familias com renda per capita de ate meio salario minimo cadastradas no CadUnico, considerando a meta minima anual de 10%.',
    'Atender ao acompanhamento continuado das familias em maior vulnerabilidade social a partir do cruzamento entre a base CECAD de referencia e os registros mensais do RMA CRAS A.2.',
    'Familias cadastradas no CadUnico com renda per capita de ate 1/2 salario minimo.',
    'ODS 1',
    'Erradicar pobreza',
    'Acompanhar a evolucao anual do percentual de familias acompanhadas pelo PAIF em relacao a base municipal de referencia.',
    'percentual de familias',
    NULL,
    10.0000,
    'RMA CRAS A.2 - Novas familias inseridas em acompanhamento. Total de familias com renda per capita de ate 1/2 salario minimo no CadUnico x 10% = meta. Total de novas familias acompanhadas A.2 / meta quantitativa = percentual alcancado.',
    'CECAD para base de familias com renda per capita de ate 1/2 salario minimo e RMA CRAS - bloco A.2 para o acompanhamento mensal.',
    'Consideram-se as familias com renda per capita de ate 1/2 salario minimo na base familia de referencia e os novos acompanhamentos informados no campo A.2 do RMA CRAS no ano de apuracao.',
    'Total de familias com renda per capita de ate 1/2 salario minimo na base familia de referencia x 10% = meta quantitativa. Soma mensal do A.2 do RMA CRAS no ano / meta quantitativa x 100 = percentual alcancado.',
    'Demonstrar a evolucao do acompanhamento das familias com renda per capita de ate 1/2 salario minimo ao longo do ano, com total acumulado e comparativo com a meta.',
    'automatico',
    'mensal',
    1
WHERE NOT EXISTS (
    SELECT 1 FROM ppa_indicadores WHERE codigo = 'PPA-ACOMPANHAR-FAMILIAS-MEIO-SM-PAIF'
);

INSERT INTO ppa_indicadores (
    codigo,
    numero_programa,
    nome,
    objetivo,
    justificativa,
    publico_alvo,
    ods_codigo,
    ods_descricao,
    meta_ods,
    unidade_medida,
    indice_recente,
    indice_futuro,
    memoria_calculo,
    fonte_dados,
    criterio_utilizado,
    forma_calculo,
    resultado_esperado,
    tipo_alimentacao,
    periodicidade,
    status
)
SELECT
    'PPA-ACOMPANHAR-BPC-PAIF',
    147,
    'Acompanhar 10% dos membros do BPC pelo Servico de Protecao e Atendimento Integral a Familia (PAIF)',
    'Monitorar o acompanhamento socioassistencial das familias com membros beneficiarios do BPC, considerando a meta minima anual de 10%.',
    'Atender ao acompanhamento continuado das familias com membros beneficiarios do BPC a partir do cruzamento entre a base CECAD de referencia e os registros mensais do RMA CRAS B.4.',
    'Familias com membros beneficiarios do BPC residentes no municipio.',
    'ODS 1',
    'Erradicar pobreza',
    'Acompanhar a evolucao anual do percentual de familias com membros do BPC acompanhadas pelo PAIF em relacao a base municipal de referencia.',
    'percentual de familias / individuos',
    NULL,
    10.0000,
    'RMA CRAS B.4 - Novas familias inseridas em acompanhamento com membros beneficiarios do BPC. Total de familias do BPC residentes no municipio x 10% = meta. Total de novas familias acompanhadas B.4 / meta quantitativa = percentual alcancado.',
    'CECAD para base de familias com membros beneficiarios do BPC e RMA CRAS - bloco B.4 para o acompanhamento mensal.',
    'Consideram-se as familias com pelo menos um membro com BPC na base pessoa de referencia e os novos acompanhamentos informados no campo B.4 do RMA CRAS no ano de apuracao.',
    'Total de familias com membros do BPC na base pessoa de referencia x 10% = meta quantitativa. Soma mensal do B.4 do RMA CRAS no ano / meta quantitativa x 100 = percentual alcancado.',
    'Demonstrar a evolucao do acompanhamento das familias com membros beneficiarios do BPC ao longo do ano, com total acumulado e comparativo com a meta.',
    'automatico',
    'mensal',
    1
WHERE NOT EXISTS (
    SELECT 1 FROM ppa_indicadores WHERE codigo = 'PPA-ACOMPANHAR-BPC-PAIF'
);

INSERT INTO ppa_indicadores (
    codigo,
    numero_programa,
    nome,
    objetivo,
    justificativa,
    publico_alvo,
    ods_codigo,
    ods_descricao,
    meta_ods,
    unidade_medida,
    indice_recente,
    indice_futuro,
    memoria_calculo,
    fonte_dados,
    criterio_utilizado,
    forma_calculo,
    resultado_esperado,
    tipo_alimentacao,
    periodicidade,
    status
)
SELECT
    'PPA-CREAS-MULHERES-F1',
    151,
    'Acompanhar novos casos de mulheres no servico de atendimento especializado a familias e individuos no CREAS',
    'Monitorar os novos casos de mulheres adultas vitimas de violencia intrafamiliar inseridas em acompanhamento no CREAS ao longo do ano.',
    'Acompanhar a execucao da protecao social especial por meio da leitura mensal do RMA CREAS, com foco nos registros do bloco F.1.',
    'Mulheres adultas de 18 a 59 anos vitimas de violencia intrafamiliar acompanhadas pelo CREAS.',
    'ODS 5',
    'Igualdade de genero',
    'Ampliar o acompanhamento especializado de mulheres vitimas de violencia intrafamiliar no municipio.',
    'numero de inseridos',
    NULL,
    555.0000,
    'RMA CREAS F.1 - Mulheres adultas (18 a 59 anos) vitimas de violencia intrafamiliar (fisica, psicologica ou sexual).',
    'RMA CREAS - bloco F.1.',
    'Consideram-se os novos casos informados mensalmente no campo F.1 do RMA CREAS no ano de apuracao mais recente disponivel.',
    'Soma mensal do campo F.1 do RMA CREAS no ano de apuracao. O percentual alcancado corresponde ao total acumulado no ano dividido pela meta anual do indicador.',
    'Demonstrar a evolucao mensal e o acumulado anual de novos casos de mulheres acompanhadas no CREAS em relacao a meta anual.',
    'automatico',
    'mensal',
    1
WHERE NOT EXISTS (
    SELECT 1 FROM ppa_indicadores WHERE codigo = 'PPA-CREAS-MULHERES-F1'
);

INSERT INTO ppa_indicadores (
    codigo,
    numero_programa,
    nome,
    objetivo,
    justificativa,
    publico_alvo,
    ods_codigo,
    ods_descricao,
    meta_ods,
    unidade_medida,
    indice_recente,
    indice_futuro,
    memoria_calculo,
    fonte_dados,
    criterio_utilizado,
    forma_calculo,
    resultado_esperado,
    tipo_alimentacao,
    periodicidade,
    status
)
SELECT
    'PPA-CREAS-PAEFI-A2',
    150,
    'Novas pessoas ou familias pelo servico de atendimento especializado a familias e individuos nos CREAS',
    'Monitorar os novos casos de familias ou individuos inseridos em acompanhamento pelo PAEFI nos CREAS ao longo do ano.',
    'Acompanhar a demanda de atendimento especializado nos CREAS por meio da leitura mensal do RMA CREAS, com foco nos registros do bloco A.2.',
    'Pessoas ou familias que iniciaram acompanhamento no PAEFI durante o periodo avaliado.',
    'ODS 16',
    'Paz, justica e instituicoes eficazes',
    'Monitorar a entrada de novos casos no acompanhamento especializado do PAEFI.',
    'numero de atendidos',
    3299.0000,
    3299.0000,
    'RMA CREAS A.2 - Novos casos (familias ou individuos) inseridos no acompanhamento do PAEFI, durante o periodo de referencia.',
    'RMA CREAS - bloco A, item A.2.',
    'Consideram-se novos casos, ou seja, individuos ou familias que iniciaram acompanhamento no PAEFI no periodo avaliado.',
    'Soma mensal do campo A.2 do RMA CREAS no ano de apuracao. O valor absoluto apurado corresponde diretamente ao resultado do indicador.',
    'Monitorar a demanda de atendimento especializado nos CREAS por meio do total acumulado de novos casos do PAEFI no ano.',
    'automatico',
    'mensal',
    1
WHERE NOT EXISTS (
    SELECT 1 FROM ppa_indicadores WHERE codigo = 'PPA-CREAS-PAEFI-A2'
);

INSERT INTO ppa_indicadores (
    codigo,
    numero_programa,
    nome,
    objetivo,
    justificativa,
    publico_alvo,
    ods_codigo,
    ods_descricao,
    meta_ods,
    unidade_medida,
    indice_recente,
    indice_futuro,
    memoria_calculo,
    fonte_dados,
    criterio_utilizado,
    forma_calculo,
    resultado_esperado,
    tipo_alimentacao,
    periodicidade,
    status
)
SELECT
    'PPA-CREAS-MSE-J4',
    153,
    'Novos casos de adolescentes inseridos em acompanhamento de medidas socioeducativas nos CREAS',
    'Monitorar os novos adolescentes inseridos em acompanhamento de medidas socioeducativas nos CREAS ao longo do ano.',
    'Acompanhar a execucao do acompanhamento socioeducativo nos CREAS por meio da leitura mensal do RMA CREAS, com foco nos registros do bloco J.4.',
    'Adolescentes em cumprimento de medidas socioeducativas (LA e/ou PSC) inseridos em acompanhamento no periodo.',
    'ODS 16',
    'Paz, justica e instituicoes eficazes',
    'Monitorar a entrada de novos adolescentes em acompanhamento de medidas socioeducativas nos CREAS.',
    'numero de inseridos',
    NULL,
    90.0000,
    'RMA CREAS J.4 - Total de novos adolescentes em cumprimento de Medidas Socioeducativas (LA e/ou PSC), inseridos em acompanhamento no periodo de referencia.',
    'RMA CREAS - bloco J.4.',
    'Consideram-se os novos adolescentes em cumprimento de medidas socioeducativas inseridos em acompanhamento no periodo avaliado.',
    'Soma mensal do campo J.4 do RMA CREAS no ano de apuracao. O valor absoluto apurado corresponde diretamente ao resultado do indicador.',
    'Monitorar a demanda de acompanhamento de medidas socioeducativas nos CREAS por meio do total acumulado de novos adolescentes no ano.',
    'automatico',
    'mensal',
    1
WHERE NOT EXISTS (
    SELECT 1 FROM ppa_indicadores WHERE codigo = 'PPA-CREAS-MSE-J4'
);

INSERT INTO ppa_indicadores (
    codigo,
    numero_programa,
    nome,
    objetivo,
    justificativa,
    publico_alvo,
    ods_codigo,
    ods_descricao,
    meta_ods,
    unidade_medida,
    indice_recente,
    indice_futuro,
    memoria_calculo,
    fonte_dados,
    criterio_utilizado,
    forma_calculo,
    resultado_esperado,
    tipo_alimentacao,
    periodicidade,
    status
)
SELECT
    'PPA-CREAS-CRIANCAS-ADOLESCENTES-C1A5',
    152,
    'Novos casos de criancas e adolescentes no servico de atendimento especializado a familias e individuos nos CREAS',
    'Monitorar os novos casos de criancas e adolescentes em situacoes de violencia ou violacoes inseridos no PAEFI ao longo do ano.',
    'Acompanhar a demanda de atendimento especializado a criancas e adolescentes nos CREAS por meio da leitura mensal do RMA CREAS, com foco na somatoria dos itens C.1 a C.5.',
    'Criancas e adolescentes em situacoes de violencia ou violacoes que ingressaram no PAEFI durante o periodo de referencia.',
    'ODS 16',
    'Paz, justica e instituicoes eficazes',
    'Monitorar a entrada de novos casos de criancas e adolescentes em acompanhamento especializado nos CREAS.',
    'numero de inseridos',
    NULL,
    2260.0000,
    'RMA CREAS bloco C - somatoria dos itens C.1 a C.5: criancas ou adolescentes vitimas de violencia intrafamiliar, abuso sexual, exploracao sexual, negligencia/abandono e trabalho infantil.',
    'RMA CREAS - bloco C, itens C.1 a C.5.',
    'Consideram-se os novos casos de criancas e adolescentes em situacoes de violencia ou violacoes registrados nos itens C.1 a C.5 do RMA CREAS no periodo avaliado.',
    'Soma mensal dos campos C.1, C.2, C.3, C.4 e C.5 do RMA CREAS no ano de apuracao. O valor absoluto apurado corresponde diretamente ao resultado do indicador.',
    'Monitorar a demanda de atendimento de criancas e adolescentes nos CREAS por meio do total acumulado anual de novos casos no PAEFI.',
    'automatico',
    'mensal',
    1
WHERE NOT EXISTS (
    SELECT 1 FROM ppa_indicadores WHERE codigo = 'PPA-CREAS-CRIANCAS-ADOLESCENTES-C1A5'
);

INSERT INTO ppa_indicadores (
    codigo,
    numero_programa,
    nome,
    objetivo,
    justificativa,
    publico_alvo,
    ods_codigo,
    ods_descricao,
    meta_ods,
    unidade_medida,
    indice_recente,
    indice_futuro,
    memoria_calculo,
    fonte_dados,
    criterio_utilizado,
    forma_calculo,
    resultado_esperado,
    tipo_alimentacao,
    periodicidade,
    status
)
SELECT
    'PPA-CRAS-ATENDIMENTOS-C1',
    158,
    'Numero de atendimentos particularizados dos CRAS referentes a protecao social basica',
    'Monitorar o total de atendimentos individualizados realizados pelos CRAS no ambito da protecao social basica ao longo do ano.',
    'Acompanhar o volume de atendimentos particularizados dos CRAS por meio da leitura mensal do RMA CRAS, com foco nos registros do bloco C.1.',
    'Usuarios atendidos individualmente pelos CRAS no periodo de referencia.',
    'ODS 1',
    'Erradicar pobreza',
    'Monitorar o volume anual de atendimentos individualizados da protecao social basica.',
    'numero de atendimentos',
    NULL,
    90000.0000,
    'RMA CRAS C.1 - Total de atendimentos individualizados realizados, no periodo de referencia.',
    'RMA CRAS - bloco C, item C.1.',
    'Consideram-se os atendimentos individualizados realizados pelos CRAS no periodo avaliado.',
    'Soma mensal do campo C.1 do RMA CRAS no ano de apuracao. O valor absoluto apurado corresponde diretamente ao resultado do indicador.',
    'Monitorar o volume anual de atendimentos particularizados dos CRAS por meio do total acumulado no ano.',
    'automatico',
    'mensal',
    1
WHERE NOT EXISTS (
    SELECT 1 FROM ppa_indicadores WHERE codigo = 'PPA-CRAS-ATENDIMENTOS-C1'
);

INSERT INTO ppa_indicadores (
    codigo,
    numero_programa,
    nome,
    objetivo,
    justificativa,
    publico_alvo,
    ods_codigo,
    ods_descricao,
    meta_ods,
    unidade_medida,
    indice_recente,
    indice_futuro,
    memoria_calculo,
    fonte_dados,
    criterio_utilizado,
    forma_calculo,
    resultado_esperado,
    tipo_alimentacao,
    periodicidade,
    status
)
SELECT
    'PPA-CRAS-ATUALIZACAO-C3',
    121,
    'Taxa de atualizacao cadastral das familias ate 1/2 salario minimo de renda per capita no CadUnico',
    'Monitorar o encaminhamento de familias para atualizacao cadastral no Cadastro Unico pelos CRAS ao longo do ano.',
    'Acompanhar a dinamica de atualizacao cadastral das familias com renda per capita de ate 1/2 salario minimo por meio da leitura mensal do RMA CRAS, com foco nos registros do bloco C.3.',
    'Familias encaminhadas para atualizacao cadastral no Cadastro Unico.',
    'ODS 1',
    'Erradicar pobreza',
    'Monitorar o volume anual de encaminhamentos para atualizacao cadastral no CadUnico.',
    'cadastros atualizados individuos',
    NULL,
    85.0000,
    'RMA CRAS C.3 - Familias encaminhadas para atualizacao cadastral no Cadastro Unico.',
    'RMA CRAS - bloco C, item C.3.',
    'Consideram-se as familias encaminhadas para atualizacao cadastral no periodo avaliado.',
    'Soma mensal do campo C.3 do RMA CRAS no ano de apuracao. O valor absoluto apurado corresponde diretamente ao resultado do indicador.',
    'Monitorar o total anual de familias encaminhadas para atualizacao cadastral no CadUnico.',
    'automatico',
    'mensal',
    1
WHERE NOT EXISTS (
    SELECT 1 FROM ppa_indicadores WHERE codigo = 'PPA-CRAS-ATUALIZACAO-C3'
);

UPDATE ppa_indicadores
SET nome = 'Taxa de atualizacao cadastral das familias ate 1/2 salario minimo de renda per capita no CadUnico',
    objetivo = 'Monitorar a taxa de atualizacao cadastral das familias com renda per capita de ate 1/2 salario minimo inscritas no CadUnico.',
    justificativa = 'Acompanhar a qualidade cadastral das familias com renda per capita de ate 1/2 salario minimo por meio da comparacao entre a base total elegivel e os cadastros atualizados em ate 24 meses na referencia CECAD.',
    publico_alvo = 'Familias inscritas no CadUnico com renda per capita de ate 1/2 salario minimo.',
    meta_ods = 'Monitorar a qualidade das informacoes cadastrais e apoiar estrategias de atualizacao do CadUnico.',
    unidade_medida = 'percentual',
    indice_recente = NULL,
    indice_futuro = 85.0000,
    memoria_calculo = 'CECAD - total de familias com renda per capita de ate 1/2 salario minimo e total dessas familias com cadastro atualizado em ate 24 meses.',
    fonte_dados = 'CECAD - base pessoa para enquadramento de renda e base familia para data de atualizacao cadastral.',
    criterio_utilizado = 'Consideram-se familias distintas com renda per capita de ate 1/2 salario minimo na referencia mais recente e, no numerador, apenas aquelas cuja data de atualizacao esteja dentro do prazo de 24 meses.',
    forma_calculo = 'Total de familias com cadastro atualizado em ate 24 meses dividido pelo total de familias com renda per capita de ate 1/2 salario minimo, multiplicado por 100. Para o painel de execucao, a meta operacional corresponde a 85% da base de referencia.',
    resultado_esperado = 'Monitorar a taxa de atualizacao cadastral e avaliar a efetividade das estrategias de atualizacao do CadUnico.',
    tipo_alimentacao = 'automatico',
    periodicidade = 'anual',
    status = 1
WHERE codigo = 'PPA-CRAS-ATUALIZACAO-C3';
