CREATE TABLE `ppa_indicadores` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `codigo` varchar(50) NOT NULL,
  `numero_programa` int(11) DEFAULT NULL,
  `nome` varchar(255) NOT NULL,
  `objetivo` text DEFAULT NULL,
  `justificativa` text DEFAULT NULL,
  `publico_alvo` varchar(255) DEFAULT NULL,
  `ods_codigo` varchar(50) DEFAULT NULL,
  `ods_descricao` varchar(255) DEFAULT NULL,
  `meta_ods` text DEFAULT NULL,
  `unidade_medida` varchar(100) DEFAULT NULL,
  `indice_recente` decimal(15,4) DEFAULT NULL,
  `indice_futuro` decimal(15,4) DEFAULT NULL,
  `memoria_calculo` text DEFAULT NULL,
  `fonte_dados` text DEFAULT NULL,
  `criterio_utilizado` text DEFAULT NULL,
  `forma_calculo` text DEFAULT NULL,
  `resultado_esperado` text DEFAULT NULL,
  `tipo_alimentacao` enum('automatico','manual','hibrido') NOT NULL DEFAULT 'manual',
  `periodicidade` enum('mensal','bimestral','trimestral','quadrimestral','semestral','anual') NOT NULL DEFAULT 'anual',
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ppa_indicadores_codigo` (`codigo`),
  KEY `idx_ppa_indicadores_programa` (`numero_programa`),
  KEY `idx_ppa_indicadores_status` (`status`),
  KEY `idx_ppa_indicadores_tipo_alimentacao` (`tipo_alimentacao`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
